[features]
seeds = false
skip-lint = false
[programs.localnet]
swap = "DMdtaoH7kM6U73HoCar2J97kVu63ncHCfgYKLNAfrgXa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hieule/.config/solanalocal/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
