[features]
seeds = false
skip-lint = false
[programs.localnet]
swap = "Hj3vPRraqqFSAcbmRWx3emQE2o7wchznAWFsn6J3tSt5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hieule/.config/solanalocal/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
